#!/bin/sh

# Set archive log mode and enable GG replication
ORACLE_SID=ORCLCDB
export ORACLE_SID
sqlplus /nolog <<- EOF
	CONNECT sys/SeCrEtPassWord_1234 AS SYSDBA
	alter system set db_recovery_file_dest_size = 10G;
	alter system set db_recovery_file_dest = '/opt/oracle/oradata/recovery_area' scope=spfile;
	shutdown immediate
	startup mount
	alter database archivelog;
	alter database open;
        -- Should show "Database log mode: Archive Mode"
	archive log list
	exit;
EOF

# Enable LogMiner required database features/settings
sqlplus sys/SeCrEtPassWord_1234@//localhost:1521/ORCLCDB as sysdba <<- EOF
  ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;
  ALTER PROFILE DEFAULT LIMIT FAILED_LOGIN_ATTEMPTS UNLIMITED;
  exit;
EOF

# Create Log Miner Tablespace and User
sqlplus sys/SeCrEtPassWord_1234@//localhost:1521/ORCLCDB as sysdba <<- EOF
  CREATE TABLESPACE LOGMINER_TBS DATAFILE '/opt/oracle/oradata/ORCLCDB/logminer_tbs.dbf' SIZE 25M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED;
  exit;
EOF

sqlplus sys/SeCrEtPassWord_1234@//localhost:1521/ORCLPDB1 as sysdba <<- EOF
  CREATE TABLESPACE LOGMINER_TBS DATAFILE '/opt/oracle/oradata/ORCLCDB/ORCLPDB1/logminer_tbs.dbf' SIZE 25M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED;
  exit;
EOF

sqlplus sys/SeCrEtPassWord_1234@//localhost:1521/ORCLCDB as sysdba <<- EOF
  CREATE USER VKS IDENTIFIED BY dbz DEFAULT TABLESPACE LOGMINER_TBS QUOTA UNLIMITED ON LOGMINER_TBS CONTAINER=ALL;

  GRANT CREATE SESSION TO VKS CONTAINER=ALL;
  GRANT SET CONTAINER TO VKS CONTAINER=ALL;
  GRANT SELECT ON V_\$DATABASE TO VKS CONTAINER=ALL;
  GRANT FLASHBACK ANY TABLE TO VKS CONTAINER=ALL;
  GRANT SELECT ANY TABLE TO VKS CONTAINER=ALL;
  GRANT SELECT_CATALOG_ROLE TO VKS CONTAINER=ALL;
  GRANT EXECUTE_CATALOG_ROLE TO VKS CONTAINER=ALL;
  GRANT SELECT ANY TRANSACTION TO VKS CONTAINER=ALL;
  GRANT SELECT ANY DICTIONARY TO VKS CONTAINER=ALL;
  GRANT LOGMINING TO VKS CONTAINER=ALL;

  GRANT CREATE TABLE TO VKS CONTAINER=ALL;
  GRANT LOCK ANY TABLE TO VKS CONTAINER=ALL;
  GRANT CREATE SEQUENCE TO VKS CONTAINER=ALL;

  GRANT EXECUTE ON DBMS_LOGMNR TO VKS CONTAINER=ALL;
  GRANT EXECUTE ON DBMS_LOGMNR_D TO VKS CONTAINER=ALL;
  GRANT SELECT ON V_\$LOGMNR_LOGS TO VKS CONTAINER=ALL;
  GRANT SELECT ON V_\$LOGMNR_CONTENTS TO VKS CONTAINER=ALL;
  GRANT SELECT ON V_\$LOGFILE TO VKS CONTAINER=ALL;
  GRANT SELECT ON V_\$ARCHIVED_LOG TO VKS CONTAINER=ALL;
  GRANT SELECT ON V_\$ARCHIVE_DEST_STATUS TO VKS CONTAINER=ALL;

  exit;
EOF

sqlplus sys/SeCrEtPassWord_1234@//localhost:1521/ORCLPDB1 as sysdba <<- EOF
  CREATE USER vks_pdb_user IDENTIFIED BY SeCrEtPassWord_1234;
  GRANT CONNECT TO vks_pdb_user;
  GRANT CREATE SESSION TO vks_pdb_user;
  GRANT CREATE TABLE TO vks_pdb_user;
  GRANT CREATE SEQUENCE to vks_pdb_user;
  ALTER USER vks_pdb_user QUOTA 100M on users;
  exit;
EOF